version: '3'

services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD: cryptosignal
      POSTGRES_DB: cryptosignal
      POSTGRES_USER: cryptosignal
    ports:
      - "5432:5432"

  app:
    image: crypto-signal
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - SETTINGS_SELECTED_TASK=simple_bot
      - SETTINGS_UPDATE_INTERVAL=43200
      - DATABASE_ENGINE=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=cryptosignal
      - DATABASE_PASSWORD=cryptosignal
    depends_on:
      - db
    ports:
      - "5000:5000"

  reporter:
    image: crypto-signal
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - SETTINGS_SELECTED_TASK=reporter
      - SETTINGS_UPDATE_INTERVAL=43200
      - DATABASE_ENGINE=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=cryptosignal
      - DATABASE_PASSWORD=cryptosignal
    depends_on:
      - db

networks:
  frontend-apis:
  backend-apis:
  default:
#  certs:
#    external: true
#  nginx-log:
#    external: true
